unstoppabledomains/domain-profiles

- packages/config/CHANGELOG.md
- packages/config/package.json
- packages/config/src/env/production.ts
As part of the migration to https://ud.me, the config client URL must be updated.
> Update client URL to https://ud.me

- package.json
- packages/ui-components/package.json
- packages/ui-components/src/components/Chat/modal/dm/ConversationPreview.tsx
- packages/ui-components/src/components/Chat/protocol/xmtp.ts
- yarn.lock
The current implementation does a lot of pre-loading of XMTP conversation data. This approach does not scale well for accounts with large number of existing conversations. The new implementation only renders conversation data for elements that are currently visible on the screen.
> Lazy load conversation preview

- packages/ui-components/src/actions/domainProfileActions.ts
- packages/ui-components/src/components/Chat/modal/group/CommunityList.tsx
- packages/ui-components/src/components/Domain/DomainPreview.tsx
- packages/ui-components/src/components/Header/AccountButton.tsx
- packages/ui-components/src/lib/types/domain.ts
- server/pages/[domain]/index.page.tsx
Update the `getProfileData()` method to require the requested fields to be provided explicitly. Ensures the app is only requesting the data it needs, and not causing server processing delays without reason.
> Request only the required profile data

- packages/ui-components/src/components/CryptoAddresses/CryptoAddress.tsx
- server/pages/[domain]/index.page.test.tsx
- server/pages/[domain]/index.page.tsx
Instead of retrieving the on-chain records as part of the main `/public/<domain>` request to the profile API, render them on the client side at page load time. This will enable improved cache management with faster and more accurate display of on-chain records.
> Render on-chain records at client side

- packages/ui-components/src/lib/types/domain.ts
- server/pages/[domain]/index.page.test.tsx
- server/pages/[domain]/index.page.tsx
UD.me profiles to start using a newly introduced domain profile data point for a domain seller email: `profile.publicDomainSellerEmail`.
> [ECW-2729] Transition domain for sale flag to off-chain domain profile data point

- README.md
- package.json
- packages/ui-components/CHANGELOG.md
- packages/ui-components/package.json
- packages/ui-components/src/components/Chat/modal/ChatModal.tsx
- packages/ui-components/src/components/Header/AccountButton.tsx
There is a race condition when loading user settings. Under certain conditions, the user settings are not reliably loaded, which causes previously blocked conversations to appear in the XMTP inbox. This is obviously not desirable.
> Refactor loading of user settings

- packages/ui-components/CHANGELOG.md
- packages/ui-components/package.json
- yarn.lock
Dependents of this package will likely want to use their own UI-kit context. To allow them to do this, we need to move the UI-kit depending on the peers.
> Use UI-kit as peer dependency

- packages/ui-components/CHANGELOG.md
- packages/ui-components/package.json
- packages/ui-components/src/components/Badges/BadgePopupModal.tsx
- packages/ui-components/src/components/Domain/DomainPreview.tsx
- server/pages/[domain]/index.page.tsx
To allow using `<DomainPreview />` component without Messaging context, would be good to pass current dependencies via props.
> Move from chat context dependence to passing props

- client.jest.config.ts
- packages/config/src/env/default.ts
- server/lib/ipfs.test.ts
- server/lib/ipfs.ts
- server/pages/[domain]/index.page.tsx
If an IPFS content record is provided, it should be normalized to account for known prefixes like `/ipfs` and `/ipns`. If a known prefix is not provided with the hash, use a default prefix `/ipfs`
> Normalize IPFS hash

- packages/ui-components/src/components/Chat/UnstoppableMessaging.tsx
- server/pages/[domain]/index.page.tsx
The feature was previously disabled for non-Unstoppable domains. This PR opens the feature to all domains, provided the domain's on-chain records include verified ownership proofs.
> Enable token gallery for ENS domains

- packages/ui-components/src/components/Wallet/ProfileManager.tsx
- server/package.json
- yarn.lock
Ensure the latest version of the Push Protocol alpha SDK is being referenced by node_modules build. The `/server` package was importing the stable SDK version, while the `ui-components` package was importing the alpha. This caused the SDK to be an unexpected level at build time, and features not working as expected.
> Ensure Push Protocol SDK at latest version

- server/pages/[domain]/index.page.tsx
When processing Webacy data, incorrect assumptions were made about the structure of the return format. Null checking should handle data that is received in different format.
> HOTFIX: Typecheck webacy results

- packages/config/src/env/default.ts
- packages/config/src/env/production.ts
- packages/config/src/env/types.ts
- packages/ui-components/src/lib/formOpenseaLink.ts
- server/pages/[domain]/index.page.tsx
The registry value `0x00000000000c2e074ec69a0dfb2997ba6c7d2e1e` provided by the resolution service is not the smart contract address expected by OpenSea. Update the config to use the expected smart contract address `0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85` for ENS domains.
> Use correct smart contract address for ENS listing on OpenSea

- packages/ui-components/src/actions/domainProfileActions.ts
- packages/ui-components/src/components/Header/ProfileSearchBar.tsx
- packages/ui-components/src/components/Image/Logo.tsx
- packages/ui-components/src/lib/domain/format.ts
- packages/ui-components/src/lib/seo.ts
- packages/ui-components/src/lib/types/domain.ts
- packages/ui-components/src/lib/types/seo.ts
- packages/ui-components/src/locales/en.json
- server/next.config.js
- server/pages/[domain]/index.page.tsx
- server/pages/_document.page.tsx
- server/pages/index.page.tsx
- server/styles/pages/index.styles.ts
There has long been missing a landing page for https://ud.me, and instead has been redirecting to Unstoppable Domains homepage. This PR creates a basic landing page that can:
- Search for existing domain profiles
- Search for wallet addresses
- Suggest domains available for purchase
> Basic landing page

- README.md
- examples/unstoppable-messaging/pages/_app.page.tsx
- packages/ui-components/CHANGELOG.md
- packages/ui-components/package.json
- packages/ui-components/src/components/Header/LoginButton.tsx
- packages/ui-components/src/components/TokenGallery/NFTGalleryCarousel.tsx
- packages/ui-components/src/providers/BaseProvider.tsx
- packages/ui-components/src/providers/DomainConfigProvider.tsx
- packages/ui-components/src/providers/TokenGalleryProvider.tsx
- packages/ui-components/src/providers/UnstoppableMessagingProvider.tsx
- packages/ui-components/src/tests/test-utils.tsx
- server/pages/[domain]/index.page.tsx
- server/pages/_app.page.tsx
- server/tests/test-utils.tsx
- yarn.lock
Currently, <BaseProvider/> is used in every Provider, as well as in the main App Wrapper. This creates unnecessary nesting, which can potentially cause issues.
In this PR, we:
- Reorganize context providers nesting
- Fix the react "key" issue in the console
- Stop passing `onLoginComplete` to Button as a prop
- Move `notistack` to `peerDependencies`
> Reorganize context providers nesting

- client.jest.config.ts
- packages/ui-components/CHANGELOG.md
- packages/ui-components/package.json
- packages/ui-components/src/components/Chat/protocol/push.ts
- packages/ui-components/src/components/Chat/protocol/types.ts
- packages/ui-components/src/components/Chat/protocol/upload.ts
- packages/ui-components/src/components/Chat/protocol/xmtp.ts
- packages/ui-components/src/lib/sleep.ts
- server/package.json
- yarn.lock
The previously used storage service from https://web3.storage has been discontinued, and clients are no longer able to upload new files using this approach. There is a new Web3 file management service from the same provider, but requires code and key updates in order to work.
This PR is based on the XMTP sample app update: https://github.com/xmtp-labs/xmtp-inbox-web/pull/416
Notes:
- Attachments UX remains unchanged, the underlying upload mechanism is only updated
- Previously uploaded files are still available
> Migrate XMTP file uploads to W3-up service

- packages/ui-components/CHANGELOG.md
- packages/ui-components/package.json
- packages/ui-components/src/components/Chat/modal/ChatModal.tsx
- packages/ui-components/src/components/Chat/modal/group/Community.tsx
- packages/ui-components/src/components/Chat/modal/group/CommunityConversationBubble.tsx
- packages/ui-components/src/components/Chat/modal/styles.ts
- packages/ui-components/src/components/Chat/protocol/push.ts
- packages/ui-components/src/components/Domain/DomainListModal.tsx
- packages/ui-components/src/locales/en.json
> Add mouseover effect to group chat options

- packages/ui-components/CHANGELOG.md
- packages/ui-components/package.json
- packages/ui-components/src/components/Chat/modal/ChatModal.tsx
- packages/ui-components/src/components/Chat/modal/group/Community.tsx
- packages/ui-components/src/components/Chat/modal/group/CommunityConversationBubble.tsx
- packages/ui-components/src/components/Chat/modal/group/CommunityList.tsx
- packages/ui-components/src/components/Chat/modal/group/CommunityPreview.tsx
- packages/ui-components/src/components/Chat/modal/styles.ts
- packages/ui-components/src/components/CopyToClipboard.tsx
- packages/ui-components/src/locales/en.json
When viewing the list of member groups, incoming messages should dynamically update and re-order the list.
> Group chat tab with dynamic preview and sorting

- packages/ui-components/package.json
- packages/ui-components/src/components/Chat/modal/group/CommunityConversationBubble.tsx
- packages/ui-components/src/components/Chat/protocol/push.ts
- yarn.lock
- Update `@pushprotocol/restapi` to latest
- Temporary message decryption logic with more robust error handling for unexpected message formats. To be removed once the Push SDK includes the error handling.
> Bump push protocol SDK version

- packages/ui-components/src/actions/domainActions.ts
Badge collection was previously handled by the UD e-commerce backend. That functionality has now been migrated to the profile service, and some adjustments can be made on the profile pages to reflect this change.
> Migrate to profile service badge collection

- packages/ui-components/src/components/Chat/UnstoppableMessaging.tsx
- packages/ui-components/src/components/Wallet/AccessEthereum.tsx
- packages/ui-components/src/lib/types/web3.ts
There is an edge case in the way the `AccessWalletModal` creates a web3context signer. The provider needs to be initialized for older (v1) push protocol accounts.
> Initialize web3context provider for push account signing

- packages/ui-components/src/components/Chat/modal/dm/ConversationCompose.tsx
- packages/ui-components/src/components/Chat/modal/group/CommunityCompose.tsx
- packages/ui-components/src/components/Chat/protocol/push.ts
- packages/ui-components/src/components/Chat/protocol/upload.ts
- packages/ui-components/src/components/Chat/protocol/xmtp.ts
- packages/ui-components/src/lib/types/domain.ts
- packages/ui-components/src/locales/en.json
A profile API endpoint is available to handle both XMTP and Push Protocol attachment uploads. This PR migrates from the 3rd party storage provider (web3.storage) to the Unstoppable Domains hosted storage.
> Consume profile API attachment endpoint

- packages/ui-components/src/components/Manage/DomainProfileModal.tsx
- packages/ui-components/src/components/Manage/Tabs/Crypto.tsx
- packages/ui-components/src/components/Manage/Tabs/Reverse.tsx
- packages/ui-components/src/components/Manage/common/CurrencyInput.tsx
- packages/ui-components/src/components/Manage/common/MultiChainInput.tsx
- packages/ui-components/src/components/Manage/common/TabHeader.tsx
- packages/ui-components/src/components/Manage/common/verification/VerificationInfoModal.tsx
- packages/ui-components/src/components/Manage/common/verification/VerifyAdornment.tsx
- packages/ui-components/src/components/Wallet/TokensPortfolio.tsx
- packages/ui-components/src/locales/en.json
Instead of waiting for on-chain records to be confirmed (up to several minutes) to verify a crypto address, allow the user to verify while they wait for confirmation. Much smoother user experience, which is now enabled by new backend logic.
> Enable address verification while on-chain records are pending

- packages/ui-components/src/components/Manage/DomainProfile.tsx
- packages/ui-components/src/components/Manage/DomainProfileModal.tsx
- packages/ui-components/src/locales/en.json
- server/pages/[domain]/index.page.tsx
On the domain management modal, we should only show on-chain actions for UNS domains that are living on the Polygon blockchain. These are the domains currently supported by Partner API v3. At a point in the future, more domains will be added to this supported user experience.
> Only display on-chain actions for UNS domains on Polygon blockchain

- cloudbuild.yaml
GCP is chaning how cloudbuild uses service accounts, so we needed to update all of our cloudbuild triggers to run as a custom service accounts. https://github.com/unstoppabledomains/infrastructure/pull/316 did this.
however, when setting service accounts, a GCS bucket needs used to store logs. need to fix/update all the cloudbuild triggers and .yaml's
https://github.com/unstoppabledomains/infrastructure/pull/325 set the production value for the GCS bucket.
This PR sets the default / staging value.
SRE-1475
https://linear.app/unstoppable-domains/issue/SRE-1475/update-cloudbuild-to-use-new-gcs-buckest
Testing:
staging cloudbuild https://console.cloud.google.com/cloud-build/builds;region=us-central1/ea3e9260-7085-4248-8a5e-d39a730d461c?project=unstoppable-domains-staging shows that logs are …
> [SRE-1475] update GCS Bucket

- packages/ui-components/src/components/Image/BaseIcon.tsx
- packages/ui-components/src/components/Image/CryptoIcon.tsx
- packages/ui-components/src/components/Image/index.ts
- packages/ui-components/src/lib/types/blockchain.ts
SVG definition from Base [brand kit](https://github.com/base-org/brand-kit/tree/7d3531058f5d89aeb627ab2045e1c5df3efb5de8).
> Include Base blockchain icon

- packages/ui-components/src/lib/types/domain.ts
- server/pages/[domain]/index.page.tsx
If the `manage` query string parameter is present, open the domain management modal on page load. If the user is not already logged in, they will be prompted to connect the appropriate wallet.
> Open management modal with query string flag

- packages/ui-components/src/components/CryptoAddresses/CryptoAddress.tsx
- packages/ui-components/src/locales/en.json
- server/pages/[domain]/index.page.tsx
Clarify the UX around the expected result of clicking a crypto icon chip on a domain profile page. Currently, all chips show a "copy icon" even though this may not be the action performed. This PR updates the chip as follows:
1. For supported single address records
- Change to a "launch" styled icon
- Add tooltip "Open in OKLink"
- Clicking the chip results in a new browser tab opening the address in blockscan explorer
1. For supported multi address records
- Change to a "menu" icon as the chip icon, to indicate options are available
- Show the "launch icon" within the opened menu
- Clicking the menu item results in a new browser tab opening the address in blockscan explorer
1. For unsupported chains
- Keep the "copy" icon
- Keep existing copy behavior
The launch icon shows that clicking …
> Clarify crypto address action UX

- packages/ui-components/src/actions/fireBlocksActions.ts
- packages/ui-components/src/hooks/useSubmitTransaction.ts
- packages/ui-components/src/lib/types/fireBlocks.ts
Tie into the existing `useSubmitTransaction()` hook to clear the operation queue for an asset. This prevents the situation where a previous abandoned operation is awaiting signature, causing the send operation to hang indefinitely.
> Ability to cancel pending operations before send operation

- packages/config/src/env/default.ts
- packages/config/src/env/types.ts
- packages/ui-components/src/actions/fireBlocksActions.ts
Add a config property to choose the asset used by default for signatures. Default to MATIC on Polygon chain, since all wallets will have this asset.
> Explicit signature asset

- packages/config/src/env/default.ts
- packages/ui-components/src/components/Wallet/DomainWalletTransactions.tsx
- packages/ui-components/src/components/Wallet/TokensPortfolio.tsx
In order to align with the mobile wallet client, use the Ethereum/ETH asset as the default for generating message signatures. Previously Polygon/MATIC asset was used as the default. Using the same default will ensure the same signature result is created across the client implementations, which is important for the functionality of some apps such as XMTP and Push Protocol.
> Use ETH asset as default for signatures

- packages/ui-components/src/components/Wallet/Client.tsx
Button text was previously not shown for mobile breakpoints, caused some UX confusion.
> Show send/receive/buy button text in mobile UX

- packages/ui-components/src/components/Wallet/Client.tsx
- packages/ui-components/src/components/Wallet/Configuration.tsx
- packages/ui-components/src/components/Wallet/Token.tsx
- packages/ui-components/src/components/Wallet/TokensPortfolio.tsx
- packages/ui-components/src/lib/types/domain.ts
A new (empty) wallet should be populated with interesting placeholder data, and the "activity" tab should be disabled.
> Improve UX for new empty wallet

- packages/ui-components/src/components/Wallet/InlineEducation.tsx
- server/pages/wallet/index.page.tsx
When inspecting the state for an existing login, there is some flicker. Add a loading state to delay display until the login details are inspected.
> Fix flicker when loading wallet landing page

- packages/ui-components/src/components/Wallet/AddressInput.tsx
- packages/ui-components/src/lib/types/domain.ts
The validation logic used to determine if a name should be resolved is too restrictive. Remove the undesirable validator and use an existing validator that has preferable logic.
> Use more generic validation to determine resolver status

- packages/ui-components/src/lib/domain/records.ts
[Linear](https://linear.app/unstoppable-domains/issue/REG-1302/bug-when-removing-solana-from-eth)
Bug for .eth domains managed on ens.domains
When removing addresses for .eth domains on ENS website, they set the address to a null address 0x00000... or 0x. We end up showing this null address in the profile page when we should hide it
> [REG-1302] Hide showing null addresses

- packages/ui-components/src/actions/fireBlocksActions.ts
When using Lite Wallet to sign a hex message such as `0x23eca67464edb5f5b81248918309675990af00436b1da7b47d625ec24c0e8be2`, the `hex` encoding parameter must be passed along with the signing request. Historically, this encoding was determined automatically on the server side but is no longer the case.
> Explicitly request hex encoding when signing messages with Lite Wallet

- packages/ui-components/src/components/Header/AccountButton.tsx
- packages/ui-components/src/components/Wallet/Configuration.tsx
- packages/ui-components/src/components/Wallet/Wallet.tsx
- server/pages/[domain]/index.page.tsx
- server/pages/badge/[badgeCode].page.tsx
- server/pages/wallet/index.page.tsx
There is an edge case where a stale refresh token results in an error retrieving a fresh access token. Currently, this results in displaying a login panel, but with no button to "continue" signing in. This PR resolves this state management so the button is displayed as expected.
> Prompt for Lite Wallet login when token refresh fails

- packages/ui-components/src/actions/fireBlocksActions.ts
- packages/ui-components/src/components/Manage/Tabs/Transfer.tsx
- packages/ui-components/src/locales/en.json
Until the backend supports the 2-stage transfer for wrapped (ERC721) ENS domains, disable support on the UI.
> Disable ENS xfer for unwrapped domains

- packages/config/src/env/default.ts
- packages/config/src/env/production.ts
- packages/config/src/env/types.ts
- packages/ui-components/src/components/Chat/modal/ChatModal.tsx
- packages/ui-components/src/components/Chat/modal/dm/Conversation.tsx
- packages/ui-components/src/components/Chat/protocol/xmtp.ts
A configurable list of wallet addresses to show by default in the XMTP chat client. By default, the following users are shown in the chat:
- Unstoppable support team
- Unstoppable Lite Wallet notifications
> Introduce XMTP conversation allowlist

- packages/ui-components/src/lib/fetchApi.ts
All client requests use a `fetchApi()` wrapper for outbound API calls. However, the wrapper does not currently use an explicit timeout. This means that the browser defaults control the request timeouts, and this can vary from browser to browser. Some examples:
- Chrome: 5 minutes
- Firefox: 90 seconds
- Safari: 60 seconds
This PR introduces an explicit default timeout of 5 minutes, and also allows an optional `timeout` parameter to be passed in order to override the timeout for specific requests.
> Allow configuration timeout on fetch wrapper

- packages/config/src/env/default.ts
- packages/config/src/env/types.ts
- packages/ui-components/src/actions/walletActions.ts
- packages/ui-components/src/components/Chat/protocol/xmtp.ts
- packages/ui-components/src/components/Manage/Tabs/Transfer.tsx
- packages/ui-components/src/components/Wallet/Configuration.tsx
- packages/ui-components/src/lib/fireBlocks/client.ts
- packages/ui-components/src/lib/types/wallet.ts
- packages/ui-components/src/locales/en.json
The device's local time plays a role in Fireblocks certificate validation and signing operations. If the local clock is out of sync by even 2 seconds, errors will occur during sign in. This PR adds a clock drift check against a time oracle provided by the Unstoppable Domains backend service. If the clock is out of sync:
- A helpful error message is show to the user
- The error is logged so that UD can have visibility to how often this scenario occurs
Example error message when clock is out of sync.
> Check for clock drift during Lite Wallet sign in

- packages/ui-components/src/components/Wallet/TokensPortfolio.tsx
Easier access to copy/paste wallet addresses from top level wallet screen.
> Include copy icon for wallets in main ULW view

- packages/ui-components/package.json
- packages/ui-components/src/hooks/useFireblocksMessageSigner.ts
- packages/ui-components/src/hooks/useFireblocksTxSigner.ts
- packages/ui-components/src/lib/fireBlocks/client.ts
- packages/ui-components/src/lib/types/fireBlocks.ts
- yarn.lock
Use the `ts-retry` package to wrap some common flaky failure paths in basic retry logic. Often when the client calls the wallet API backend, there are intermittent failures. The root cause on the wallet API failures is usually a Fireblocks upstream error, but calling the same API again after a short 100ms delay typically resolves the problem.
Used default retry count of 5.
> Add retry logic for Fireblocks signing operations

- packages/ui-components/package.json
- packages/ui-components/src/components/Wallet/Client.tsx
Currently, the "domains" tab in Unstoppable Lite Wallet shows domain portfolio valuation. However, the valuation is scoped to the UD account associated with the wallet which is a confusing user experience. Update the rendering logic to show a valuation (if present) only for domains contained in the current wallet.
> Show wallet scoped valuation if available

- server/pages/[domain]/index.page.tsx
Fastly changes the host on staging and production so we need to use x-forwarded-host to check the ud.me url against insteaad
> Fix listing page redirect

- packages/ui-components/package.json
- packages/ui-components/src/components/Wallet/Send.tsx
- packages/ui-components/src/components/Wallet/Token.tsx
The wallet service provides the max decimal length for each token. This value should be validated against user input to ensure only the expected number of decimals is provided to the backend. Otherwise a validation error will occur and the user cannot send their token.
> Validate token decimals before send

- server/pages/[domain]/index.page.tsx
Log resolvedUrl for test domain on production
> Log resolvedUrl

- server/pages/[domain]/index.page.tsx
We're unable to see the original url from inside the getServerSideProps() needed to differentiate test.com from ud.me/test.com so move the listing redirect logic to inside the Domain Profile Page component
> Move listing redirect to inside component

- server/pages/[domain]/index.page.tsx
useLayoutEffect instead of useEffect:
`Updates scheduled inside useLayoutEffect will be flushed synchronously, before the browser has a chance to paint.`
> Improve listing page redirect performance

- server/pages/[domain]/index.page.tsx
The profile page was not using the available `getBlockScanUrl()` method that already accounts for various chain formats. Using this method resolves the problem where domains minted on Base get linked to Polygon block scanner.
> Fix logic when generating link to block scanner page

- packages/config/package.json
- packages/config/src/env/default.ts
- packages/config/src/env/production.ts
- packages/config/src/launchdarkly/defaultFlagValues.ts
- packages/config/src/launchdarkly/keys.ts
- packages/ui-components/package.json
- packages/ui-components/src/components/Wallet/SelectAsset.tsx
- packages/ui-components/src/components/Wallet/Send.tsx
- packages/ui-components/src/hooks/useSubmitTransaction.ts
- packages/ui-components/src/lib/types/domain.ts
- packages/ui-components/src/lib/wallet/asset.ts
- packages/ui-components/src/lib/wallet/solana/provider.ts
- packages/ui-components/src/lib/wallet/solana/transaction.test.ts
- packages/ui-components/src/lib/wallet/solana/transaction.ts
- server.jest.config.ts
- tests/setupTests.ts
- yarn.lock
Adds the ability to send Solana SPL tokens, as well as sign Solana messages and transactions. Gated by feature flag `ud-me-enable-wallet-solana-signing`.
> Solana SPL token support

- packages/ui-components/package.json
- packages/ui-components/src/actions/fireBlocksActions.ts
- packages/ui-components/src/components/Wallet/SecurityCenterModal.tsx
- packages/ui-components/src/components/Wallet/Swap.tsx
- packages/ui-components/src/components/Wallet/TwoFactorModal.tsx
- packages/ui-components/src/components/Wallet/WalletProvider.tsx
- packages/ui-components/src/hooks/useFireblocksAccessToken.ts
- packages/ui-components/src/lib/wallet/tokens.ts
If the user leaves their browser or extension window (e.g. the sidebar) open, the access token may expire and be invalid when they next attempt to perform an operation. Set a timer to fire and refresh the token before it expires on long-lived sessions.
> Refresh access token in background

- packages/ui-components/src/components/Manage/Tabs/Profile/AddAvatarPopup.tsx
Removes option to set custom avatar URL to prevent possible explicit content from being displayed. Images that are uploaded will be validated for safe content and hosted in our bucket. We can re enable this option once we add the ability to validate avatar URLs
> Remove option to set custom avatar url

- packages/ui-components/src/components/TokenGallery/TokenGallery.tsx
Currently, the token gallery starts pre-loading NFT data as soon as the page is finished loading. Update the page to only start loading once the gallery is expanded.
> Only load NFT data when token gallery is expanded

- packages/ui-components/src/components/Wallet/SecurityCenterModal.tsx
- packages/ui-components/src/components/Wallet/WalletProvider.tsx
- packages/ui-components/src/lib/wallet/buySellCrypto.ts
- packages/ui-components/src/lib/wallet/chromeRuntime.ts
On Firefox, any runtime reference to `chrome?.*` results in an exception. This is not the behavior on chrome based browsers, even though the object is still not defined on a browser runtime there either. Update error handling and usage to account for this difference.
> Fix page load problems on Firefox browser

- packages/ui-components/package.json
- packages/ui-components/src/actions/fireBlocksActions.ts
- packages/ui-components/src/actions/walletStorageActions.ts
- packages/ui-components/src/components/Chat/storage.ts
- packages/ui-components/src/components/DropDownMenu.tsx
- packages/ui-components/src/components/Wallet/Client.tsx
- packages/ui-components/src/components/Wallet/DomainWalletTransactions.tsx
- packages/ui-components/src/components/Wallet/SecurityCenterModal.tsx
- packages/ui-components/src/components/Wallet/SelectAsset.tsx
- packages/ui-components/src/components/Wallet/SetupPinModal.tsx
- packages/ui-components/src/components/Wallet/Swap.tsx
- packages/ui-components/src/components/Wallet/TokenDetail.tsx
- packages/ui-components/src/hooks/useChromeStorage.ts
- packages/ui-components/src/hooks/useWeb3Context.tsx
- packages/ui-components/src/lib/types/walletStorage.ts
- packages/ui-components/src/lib/wallet/pin/key.test.ts
- packages/ui-components/src/lib/wallet/pin/key.ts
- packages/ui-components/src/lib/wallet/pin/locker.test.ts
- packages/ui-components/src/lib/wallet/pin/locker.ts
- packages/ui-components/src/lib/wallet/pin/store.ts
- packages/ui-components/src/lib/wallet/storage/provider.ts
- packages/ui-components/src/lib/wallet/storage/state.ts
- server/pages/wallet/index.page.tsx
Move to wallet based configuration target for certain configuration values that were previously stored locally. This allows configuration items to persist across devices.
- Banner acknowledgments
- Session timeout / PIN settings
> Use wallet k/v storage for swap preferences

- packages/ui-components/package.json
- packages/ui-components/src/lib/wallet/solana/transaction.ts
The Solana token SDK expects decimal validation prior to being called. Adding these checks to prevent errors when transferring token amounts with many decimal places.
> Validate token decimal precision when creating a Solana transaction

- packages/ui-components/package.json
- packages/ui-components/src/actions/fireBlocksActions.ts
- packages/ui-components/src/components/TokenGallery/NftCard.tsx
- packages/ui-components/src/components/TokenGallery/NftModal.tsx
- packages/ui-components/src/components/Wallet/Client.tsx
- packages/ui-components/src/components/Wallet/NftCollectionDetail.tsx
- packages/ui-components/src/components/Wallet/Send.tsx
- packages/ui-components/src/components/Wallet/SendConfirm.tsx
- packages/ui-components/src/hooks/useSubmitTransaction.ts
- packages/ui-components/src/lib/types/domain.ts
- packages/ui-components/src/lib/types/fireBlocks.ts
- packages/ui-components/src/lib/wallet/asset.ts
- packages/ui-components/src/lib/wallet/evm/abi.ts
- packages/ui-components/src/lib/wallet/evm/token.ts
- packages/ui-components/src/lib/wallet/evm/web3.ts
Enables both NFT transfers for both EVM (ERC-721) and Solana (both SPL & Token22).
https://polygonscan.com/tx/0x2f5eb38f9407362303c192db79206bf14282feecf8ddcf17f9800d692ba61857
> Enable NFT transfers within wallet
