unstoppabledomains/domain-profiles

- client.jest.config.ts
- package.json
- packages/ui-components/package.json
- packages/ui-components/src/actions/domainProfileActions.ts
- packages/ui-components/src/components/TokenGallery/NFTGalleryCarousel.tsx
- packages/ui-components/src/components/TokenGallery/NftCard.tsx
- packages/ui-components/src/components/TokenGallery/NftGalleryData.tsx
- packages/ui-components/src/components/TokenGallery/NftGalleryManager.tsx
- packages/ui-components/src/components/TokenGallery/NftGalleryView.tsx
- packages/ui-components/src/components/TokenGallery/NftModal.tsx
- packages/ui-components/src/components/TokenGallery/TokenGallery.tsx
- packages/ui-components/src/lib/types/nfts.ts
- packages/ui-components/src/providers/TokenGalleryProvider.tsx
- server/pages/[domain]/index.page.test.tsx
- tests/mocks/swiper-react/index.tsx
- yarn.lock
Add unit tests to validate profile page features.
> More robust unit tests for profile page

- README.md
- packages/ui-components/src/components/Chat/UnstoppableMessaging.tsx
Describe how developers should publish new NPM packages if applicable.
> Update README for developer usage

- packages/ui-components/src/components/Domain/SocialAccountCard.tsx
- packages/ui-components/src/components/TokenGallery/NftCard.tsx
- server/components/app/Layout.tsx
- server/pages/[domain]/index.page.test.tsx
- server/pages/[domain]/index.page.tsx
- server/pages/_app.page.tsx
- server/styles/pages/app.styles.ts
Page load on the main domain profile page has a lot of flicker and movement, and quite distracting. Add an `isLoaded` state to reduce noise during page load, and also update styling to keep loading elements in place.
> Reduce flicker on profile load

- packages/ui-components/src/components/Manage/DomainProfile.tsx
- packages/ui-components/src/components/Manage/DomainProfileModal.tsx
- packages/ui-components/src/components/Manage/Tabs/Profile/index.tsx
- packages/ui-components/src/components/TokenGallery/NFTGalleryCarousel.tsx
- packages/ui-components/src/components/TokenGallery/NftGalleryView.tsx
- packages/ui-components/src/components/TokenGallery/TokenGallery.tsx
- packages/ui-components/src/lib/domain/format.ts
- packages/ui-components/src/locales/en.json
- server/pages/[domain]/index.page.tsx
- Sizing of management tab container
- Indicate token gallery loading state in expanded view
- Token gallery collection filter should always include all items
- Add close/cancel button in top right of modal
- Repeating duplicate NFT in carousel
- Owner cannot edit token gallery items if all items hidden
> UX improvements from community feedback

- packages/ui-components/package.json
- packages/ui-components/src/components/Chat/protocol/push.ts
- yarn.lock
Upgrade from alpha version to stable.
> Bump push protocol to latest version

- packages/config/CHANGELOG.md
- packages/config/package.json
- packages/ui-components/CHANGELOG.md
- packages/ui-components/package.json
```
- Off-chain profile management React components
- On-chain records management React components
- Upgrade Push Protocol SDK packages to support token gated group chat
```
> Release @unstoppabledomains/ui-components 0.0.31

- packages/ui-components/src/actions/domainProfileActions.ts
- packages/ui-components/src/components/TokenGallery/NftGalleryData.tsx
- packages/ui-components/src/lib/types/nfts.ts
- Update the logic to determine if all NFTs loaded
- Reduce the page size requested from backend
> Improve token gallery load time

- packages/ui-components/src/components/Header/ProfileSearchBar.tsx
- packages/ui-components/src/locales/en.json
- server/styles/pages/index.styles.ts
Add the following optimizations for UX:
- Move suggested sale items to bottom of search result list
- Allow user to press "enter" to navigate to the first matching result
- Move search box closer to top of page
> Update landing page UX

- packages/ui-components/src/components/Header/LoginButton.tsx
- packages/ui-components/src/components/Image/UnstoppableAnimated.tsx
- packages/ui-components/src/components/Wallet/AccessEthereum.tsx
- packages/ui-components/src/components/Wallet/DomainWallet.tsx
- packages/ui-components/src/components/Wallet/DomainWalletList.tsx
- packages/ui-components/src/locales/en.json
- server/pages/[domain]/index.page.tsx
- server/pages/badge/[badgeCode].page.tsx
- server/styles/pages/domain.styles.ts
Add new actions to wallet tile:
- Scan QR code
- Find friends (coming soon)
> Wallet UX improvements

- packages/ui-components/src/components/Chat/modal/group/Community.tsx
- packages/ui-components/src/components/Chat/modal/group/CommunityConversationBubble.tsx
- packages/ui-components/src/components/Chat/modal/styles.ts
- packages/ui-components/src/components/Chat/protocol/push.ts
- packages/ui-components/src/components/Chat/protocol/types.ts
- packages/ui-components/src/locales/en.json
Add the ability to react to a message with an emoji.
> Emoji reaction support for group chat

- packages/ui-components/CHANGELOG.md
- packages/ui-components/package.json
- packages/ui-components/src/actions/domainActions.ts
- packages/ui-components/src/actions/domainProfileActions.ts
- packages/ui-components/src/actions/messageActions.ts
- packages/ui-components/src/components/Chat/UnstoppableMessaging.tsx
- packages/ui-components/src/components/Chat/modal/group/CommunityConversationBubble.tsx
- packages/ui-components/src/components/Chat/modal/group/CommunityPreview.tsx
- packages/ui-components/src/components/Chat/protocol/resolution.ts
- packages/ui-components/src/components/Manage/DomainProfileModal.tsx
- packages/ui-components/src/components/Manage/Tabs/Reverse.tsx
- packages/ui-components/src/lib/wallet/login.ts
- server/pages/[domain]/index.page.test.tsx
> Option to enable group chat media

- packages/ui-components/src/actions/domainActions.ts
- packages/ui-components/src/components/Image/CryptoIcon.tsx
- packages/ui-components/src/components/Wallet/DomainWallet.tsx
- packages/ui-components/src/components/Wallet/DomainWalletList.tsx
- packages/ui-components/src/components/Wallet/DomainWalletTransactions.tsx
- packages/ui-components/src/components/Wallet/index.ts
- packages/ui-components/src/lib/types/domain.ts
- packages/ui-components/src/lib/types/wallet.ts
- packages/ui-components/src/locales/en.json
- server/pages/[domain]/index.page.tsx
> Show wallet activity

- packages/ui-components/src/components/Wallet/DomainWallet.tsx
- packages/ui-components/src/components/Wallet/DomainWalletTransactions.tsx
- packages/ui-components/src/lib/types/domain.ts
> ERC20 tx history support

- packages/ui-components/src/components/Wallet/TokensPortfolio.tsx
- packages/ui-components/src/components/Wallet/index.ts
- packages/ui-components/src/lib/types/domain.ts
- packages/ui-components/src/locales/en.json
- server/pages/[domain]/index.page.tsx
> Add token portfolio card

- packages/ui-components/src/components/Manage/common/verification/VerificationInfoModal.tsx
- packages/ui-components/src/components/Manage/common/verification/VerifyAdornment.tsx
- packages/ui-components/src/components/Manage/common/verification/evm/VerificationButton.tsx
- packages/ui-components/src/components/Manage/common/verification/provider.tsx
- packages/ui-components/src/components/Manage/common/verification/types.ts
- packages/ui-components/src/components/Wallet/DomainWalletTransactions.tsx
- packages/ui-components/src/components/Wallet/TokensPortfolio.tsx
- packages/ui-components/src/locales/en.json
[Delegate.xyz](https://delegate.xyz) is a service that allows a high value vault wallet to delegate access to a lower value hot wallet. The hot wallet is used for day to day activities, like connecting to dapps, signing transacitons, airdrop claims, etc. The assets within the vault can be verified by proving ownership of the hot wallet, without the risk of losing access to the high value assets through scams or wallet drains.
The Unstoppable Domains profiles can leverage the delegate.xyz service to make profiles safer and also expand the number of wallets available to render in the aggregated portfolio, transaction and collectibles components. This means high value NFTs or any vaulted crypto can be displayed on a profile without the user having to connect or sign with their vault wallet …
> Domain portfolio support for delegate.xyz

- packages/ui-components/src/components/Manage/common/verification/VerificationInfoModal.tsx
- packages/ui-components/src/components/Manage/common/verification/types.ts
- packages/ui-components/src/locales/en.json
> Add tabs to the verification info modal

- packages/ui-components/package.json
- packages/ui-components/src/components/Chat/UnstoppableMessaging.tsx
- packages/ui-components/src/components/Header/LoginButton.tsx
- packages/ui-components/src/components/Manage/common/verification/evm/VerificationButton.tsx
- packages/ui-components/src/components/Wallet/AccessEthereum.tsx
- packages/ui-components/src/components/Wallet/AccessWallet.tsx
- packages/ui-components/src/components/Wallet/ProfileManager.tsx
- packages/ui-components/src/locales/en.json
- yarn.lock
All buttons disabled except the "retry" CTA.
> Improve UX when incorrect wallet is chosen for signature

- packages/ui-components/src/components/CryptoAddresses/CryptoAddress.tsx
> Navigate to a blockscan explorer on crypto address click

- server/pages/[domain]/index.page.tsx
Query the Unstoppable Domains identity API endpoint to determine humanity check status.
> Restore identity query

- packages/ui-components/src/locales/en.json
- server/pages/[domain]/index.page.test.tsx
- server/pages/[domain]/index.page.tsx
Show the button if a domain owner is logged in, and viewing their own domain.
> Show buy/sell crypto button on profile page

- packages/ui-components/src/components/Wallet/TokensPortfolio.tsx
> Show ERC-20 token history if available

- packages/ui-components/src/components/CryptoAddresses/CryptoAddress.tsx
- server/pages/[domain]/index.page.tsx
Add a referral code `?channelId=uns001` to instances of the OKLink blockscan references.
> Add referral code for OKLink

- packages/ui-components/src/actions/fireBlocksActions.ts
- packages/ui-components/src/components/Manage/Tabs/Wallet/Client.tsx
- packages/ui-components/src/components/Manage/Tabs/Wallet/Configuration.tsx
- packages/ui-components/src/components/Manage/Tabs/Wallet/Send.tsx
- packages/ui-components/src/components/Manage/common/ManageInput.tsx
- packages/ui-components/src/components/Wallet/DomainWallet.tsx
- packages/ui-components/src/components/Wallet/DomainWalletTransactions.tsx
- packages/ui-components/src/components/Wallet/Token.tsx
- packages/ui-components/src/components/Wallet/TokensPortfolio.tsx
- packages/ui-components/src/lib/types/domain.ts
- packages/ui-components/src/locales/en.json
> Send component for MPC Wallet

- packages/ui-components/src/actions/fireBlocksActions.ts
- packages/ui-components/src/lib/fireBlocks/client.ts
- Check for additional operation states
- Reduce complexity of polling loops
> Improve operation status polling logic for signatures and transfers

- examples/unstoppable-messaging/package.json
- packages/ui-components/package.json
- packages/ui-components/src/components/Manage/Tabs/Wallet/Header.tsx
- packages/ui-components/src/components/Wallet/WalletButton.tsx
- server/package.json
- yarn.lock
> Move to Unstoppable Wallet icon

- packages/ui-components/src/components/Manage/Tabs/Wallet/Configuration.tsx
- packages/ui-components/src/components/Manage/Tabs/Wallet/Header.tsx
- packages/ui-components/src/components/Manage/Tabs/Wallet/InlineEducation.tsx
- packages/ui-components/src/components/Manage/Tabs/Wallet/Receive.tsx
- packages/ui-components/src/components/Manage/Tabs/Wallet/Signer.tsx
Display inline education content when loading into wallet
https://github.com/unstoppabledomains/domain-profiles/assets/23408540/f17fc3f7-b495-4f4d-8eb0-1fc2001d2069
> Inline education content

- packages/ui-components/src/components/Chat/types.ts
- packages/ui-components/src/components/DropDownMenu.tsx
- packages/ui-components/src/components/Manage/Tabs/Wallet/Header.tsx
- packages/ui-components/src/components/Manage/Tabs/Wallet/InlineEducation.tsx
- packages/ui-components/src/components/index.ts
- packages/ui-components/src/hooks/index.ts
- packages/ui-components/src/lib/seo.ts
- packages/ui-components/src/lib/types/seo.ts
- packages/ui-components/src/locales/en.json
- server/pages/[domain]/index.page.tsx
- server/pages/wallet/index.page.tsx
- server/styles/pages/index.styles.ts
> Wallet landing page

- packages/config/src/env/default.ts
- packages/config/src/env/types.ts
- packages/ui-components/src/components/DropDownMenu.tsx
- packages/ui-components/src/components/Wallet/Configuration.tsx
- packages/ui-components/src/components/Wallet/Header.tsx
- packages/ui-components/src/components/Wallet/InlineEducation.tsx
- packages/ui-components/src/components/Wallet/Receive.tsx
- packages/ui-components/src/components/Wallet/Signer.tsx
- packages/ui-components/src/components/Wallet/Wallet.tsx
- packages/ui-components/src/locales/en.json
- server/next.config.js
- server/pages/wallet/index.page.tsx
Updates on wallet UX - context menus
- My profile
- My domains
- Unstoppable messaging
> Unstoppable Wallet context menus

- packages/config/src/env/default.ts
- packages/config/src/env/types.ts
- packages/ui-components/src/components/Wallet/Buy.tsx
- packages/ui-components/src/components/Wallet/Configuration.tsx
- packages/ui-components/src/components/Wallet/Receive.tsx
- packages/ui-components/src/components/Wallet/Send.tsx
- packages/ui-components/src/lib/fireBlocks/storage/state.ts
- packages/ui-components/src/lib/wallet/filter.ts
- server/pages/[domain]/index.page.tsx
- server/pages/wallet/index.page.tsx
Add configuration items to specify which tokens are supported for send, receive and buy activities.
> Wallet operation filters

- packages/config/src/env/default.ts
- packages/config/src/env/production.ts
- packages/config/src/env/types.ts
- packages/ui-components/src/actions/domainProfileActions.ts
- packages/ui-components/src/actions/walletActions.ts
- packages/ui-components/src/components/Wallet/Configuration.tsx
- packages/ui-components/src/components/Wallet/Header.tsx
- packages/ui-components/src/lib/types/wallet.ts
- packages/ui-components/src/locales/en.json
> Onboarding check for Unstoppable Wallet

- packages/ui-components/src/components/DropDownMenu.tsx
- packages/ui-components/src/components/Wallet/Client.tsx
- packages/ui-components/src/components/Wallet/Configuration.tsx
- packages/ui-components/src/components/Wallet/Header.tsx
- packages/ui-components/src/components/Wallet/ReceiveDomainModal.tsx
- packages/ui-components/src/components/Wallet/RecoverySetupModal.tsx
- packages/ui-components/src/components/Wallet/Wallet.tsx
- packages/ui-components/src/locales/en.json
> Introduce an add domain modal to populate the wallet

- packages/ui-components/src/components/Modal.tsx
- packages/ui-components/src/components/Wallet/Header.tsx
- packages/ui-components/src/components/Wallet/Signer.tsx
- packages/ui-components/src/styles/components/accessWallet.styles.ts
- packages/ui-components/src/styles/components/modal.styles.ts
Wallet popup margins and widths on modal, popovers not looking quite right. Resolve stylesheets for mobile breakpoints.
> Refine mobile breakpoints and wrapping

- packages/ui-components/src/components/Chat/modal/ChatModal.tsx
- packages/ui-components/src/components/Chat/modal/dm/Conversation.tsx
- packages/ui-components/src/components/Chat/modal/dm/ConversationStart.tsx
- packages/ui-components/src/components/Chat/modal/group/Community.tsx
- packages/ui-components/src/components/Chat/modal/group/CommunityPreview.tsx
- packages/ui-components/src/components/Chat/modal/notification/NotificationPreview.tsx
- packages/ui-components/src/components/Chat/modal/styles.ts
The previous fullscreen UX was confusing on mobile, based on user feedback. Switch to a modal view, just for mobile.
> Use modal component to wrap mobile chat UX

- packages/ui-components/src/components/Wallet/DomainWalletTransactions.tsx
- packages/ui-components/src/components/Wallet/TokensPortfolio.tsx
Resolve the `NaN` transaction fee bug.
> Transaction fee formatting

- packages/ui-components/src/components/Wallet/WalletButton.tsx
- packages/ui-components/src/lib/types/wallet.ts
> Shorten Lite Wallet title on wallet connect modal

- packages/ui-components/CHANGELOG.md
- packages/ui-components/package.json
- yarn.lock
Update the SDK version for improved performance.
> Bump @fireblocks/ncw-js-sdk to latest

- packages/ui-components/src/actions/fireBlocksActions.ts
- packages/ui-components/src/components/Wallet/AccessWallet.tsx
- packages/ui-components/src/components/Wallet/Configuration.tsx
- packages/ui-components/src/components/Wallet/Send.test.tsx
- packages/ui-components/src/components/Wallet/Send.tsx
- packages/ui-components/src/components/Wallet/SignMessage.tsx
- packages/ui-components/src/components/Wallet/SignTx.tsx
- packages/ui-components/src/components/Wallet/Wallet.tsx
- packages/ui-components/src/hooks/useFireblocksAccessToken.ts
- packages/ui-components/src/hooks/useFireblocksMessageSigner.ts
- packages/ui-components/src/hooks/useFireblocksTxSigner.ts
- packages/ui-components/src/hooks/useWeb3Context.tsx
- packages/ui-components/src/lib/fireBlocks/index.ts
- packages/ui-components/src/lib/fireBlocks/reactSigner.ts
- packages/ui-components/src/lib/fireBlocks/storage/index.ts
- packages/ui-components/src/lib/index.ts
- packages/ui-components/src/lib/types/fireBlocks.ts
- packages/ui-components/src/lib/types/index.ts
- packages/ui-components/src/locales/en.json
- packages/ui-components/src/providers/DomainConfigProvider.tsx
- packages/ui-components/src/providers/Web3ContextProvider.tsx
Add library support for prompting a user to sign a smart contract transaction. For example, the following code may be called:
```
import {useWeb3Context} from "@unstoppabledomains/ui-components"
const {web3Deps} = useWeb3Context();
const tx: CreateTransaction = {
chainId: 11155111,
contractAddress: '0x8FADE66B79cC9f707aB26799354482EB93a5B7dD',
data: '0xac9650d800000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000e410f13a8ccf03467b31fb5524f132a68525d3b9a8f17e08fa15ab8e47252f101e0238743c0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000 …
```
> Support for Lite Wallet smart contract signing

- packages/ui-components/package.json
- yarn.lock
Move to version `12.2.0` --> `12.4.1`
> Bump fireblocks SDK version

- server/next.config.js
- server/public/robots.txt
This could possibly be too restrictive, but going to start here and loosen restrictions if needed.
> Include a robot.txt to generally disallow all scraping

- packages/config/package.json
- packages/config/src/launchdarkly/defaultFlagValues.ts
- packages/ui-components/package.json
- packages/ui-components/src/actions/domainProfileActions.ts
- packages/ui-components/src/components/Manage/Tabs/DnsRecords.tsx
- packages/ui-components/src/components/Manage/Tabs/Email.tsx
- packages/ui-components/src/components/Manage/common/ManageInput.tsx
- packages/ui-components/src/components/Wallet/Configuration.tsx
- packages/ui-components/src/components/Wallet/InlineEducation.tsx
- packages/ui-components/src/components/Wallet/Receive.tsx
- packages/ui-components/src/components/Wallet/ReceiveDomainModal.tsx
- packages/ui-components/src/components/Wallet/RecoverySetupModal.tsx
- packages/ui-components/src/components/Wallet/SignForDappHeader.tsx
- packages/ui-components/src/components/Wallet/Wallet.tsx
- packages/ui-components/src/locales/en.json
Resolves the following issues:
- https://linear.app/unstoppable-domains/issue/UDM-160/force-remember-me-option-when-using-the-extension
- https://linear.app/unstoppable-domains/issue/UDM-162/add-password-reveal-for-the-recovery-kit-password
- https://linear.app/unstoppable-domains/issue/UDM-149/browser-console-runtime-errors-for-extension-popup
> Updates to extension based on team feedback

- packages/ui-components/package.json
- packages/ui-components/src/components/Manage/common/currencyRecords.ts
- packages/ui-components/src/components/Manage/common/verification/types.ts
- packages/ui-components/src/components/Wallet/AddressInput.test.tsx
- packages/ui-components/src/components/Wallet/AddressInput.tsx
- packages/ui-components/src/components/Wallet/Buy.tsx
- packages/ui-components/src/components/Wallet/Header.tsx
- packages/ui-components/src/components/Wallet/Receive.tsx
- packages/ui-components/src/components/Wallet/Send.test.tsx
- packages/ui-components/src/components/Wallet/Send.tsx
- packages/ui-components/src/hooks/useSubmitTransaction.ts
- packages/ui-components/src/lib/fireBlocks/messages/rpcHandler.ts
- packages/ui-components/src/lib/types/resolverKeys.ts
The forward address lookup for the recipient when sending crypto, needs to be updated for token family support.
> Update send resolution for token familypattern

- packages/ui-components/package.json
- packages/ui-components/src/components/Wallet/TokensPortfolio.tsx
- packages/ui-components/src/lib/wallet/index.ts
- packages/ui-components/src/lib/wallet/tokens.ts
Internal refactor, no behavior change.
> Refactor token sorting for external use

- packages/ui-components/package.json
- packages/ui-components/src/actions/walletActions.ts
- packages/ui-components/src/components/Manage/common/verification/types.ts
- packages/ui-components/src/components/Wallet/Configuration.tsx
- packages/ui-components/src/components/Wallet/DomainWalletTransactions.tsx
- packages/ui-components/src/components/Wallet/Send.tsx
- packages/ui-components/src/components/Wallet/SendConfirm.tsx
- packages/ui-components/src/components/Wallet/SignTx.tsx
- packages/ui-components/src/components/Wallet/TokensPortfolio.tsx
- packages/ui-components/src/hooks/useFireblocksMessageSigner.ts
- packages/ui-components/src/hooks/useFireblocksTxSigner.ts
- packages/ui-components/src/lib/types/wallet.ts
- packages/ui-components/src/lib/wallet/asset.ts
There are several instances of asset selection logic throughout the wallet client implementation. Refactor these to a common implementation to ensure correct logic, logging and easier maintenance.
> Refactor asset selection logic

- packages/ui-components/package.json
- packages/ui-components/src/components/Wallet/Buy.tsx
- packages/ui-components/src/components/Wallet/Client.tsx
- packages/ui-components/src/locales/en.json
- yarn.lock
Implementation for https://github.com/unstoppabledomains/resolution-browser-extension/pull/91 browser extension updates.
Allow user to buy / sell crypto directly within the wallet user experience.
https://github.com/user-attachments/assets/6b38ebce-a5b9-4c05-bac0-fdc87a15ebe4
> Open fiat ramp in popup window

- packages/config/src/env/default.ts
- packages/config/src/env/production.ts
- packages/config/src/env/staging.ts
- packages/config/src/env/types.ts
- packages/ui-components/src/actions/swingActionsV2.ts
- packages/ui-components/src/components/Wallet/Swap.tsx
- packages/ui-components/src/lib/types/swingXyzV2.ts
Support a limited set of ERC-20 swaps, specific to USDC assets on each EVM chain.
> Support for USDC swaps on EVM chains

- packages/ui-components/src/actions/fireBlocksActions.ts
- packages/ui-components/src/components/Wallet/ChangePasswordModal.tsx
- packages/ui-components/src/locales/en.json
Support both TOTP and OTP for password change.
> Support email OTP for password change

- packages/ui-components/src/components/Wallet/Client.tsx
- packages/ui-components/src/components/Wallet/Receive.tsx
- packages/ui-components/src/components/Wallet/UnlockPinModal.tsx
- packages/ui-components/src/hooks/useWeb3Context.tsx
- packages/ui-components/src/locales/en.json
Adds balance info polling to an open and unlocked wallet. Additionally, [adds a "share" button](https://linear.app/unstoppable-domains/issue/UDM-234/[extension]-receive-crypto-share-button) to the receive crypto modal to make it easier to share your address with others.
> Poll for balance change when wallet is unlocked

- packages/ui-components/package.json
- packages/ui-components/src/components/Domain/DomainProfileList.tsx
- packages/ui-components/src/components/DropDownMenu.tsx
- packages/ui-components/src/components/Wallet/Buy.tsx
- packages/ui-components/src/components/Wallet/Client.tsx
- packages/ui-components/src/components/Wallet/DomainWalletTransactions.tsx
- packages/ui-components/src/components/Wallet/Header.tsx
- packages/ui-components/src/components/Wallet/Receive.tsx
- packages/ui-components/src/components/Wallet/Send.tsx
- packages/ui-components/src/components/Wallet/Swap.tsx
- packages/ui-components/src/components/Wallet/TokensPortfolio.tsx
- packages/ui-components/src/components/Wallet/Wallet.tsx
- packages/ui-components/src/components/Wallet/WalletProvider.tsx
- packages/ui-components/src/locales/en.json
- server/pages/wallet/index.page.tsx
> Make wallet height and width reactive

- server/pages/[domain]/index.page.tsx
Now that we have migrated to new domain forwarding system we can remove our temporary solution of redirect to listing page if domain is listed
> Remove listing page redirect

- packages/ui-components/src/components/Wallet/Client.tsx
Show `.00` cents if < $1000, otherwise show whole dollars only.
> Balance specific formatting with numeral()

- packages/ui-components/package.json
- packages/ui-components/src/styles/theme/upio/index.ts
Using the UP.io style guide as reference: 
https://www.figma.com/design/Ye1S479xSF9LCApLExGkwp/%F0%9F%86%99--Styleguide?node-id=2-686&t=n50orcuh2ufkPc1r-0
> Align with UP.io Figma palette

- packages/ui-components/src/actions/domainProfileActions.ts
- packages/ui-components/src/components/Chat/modal/group/Community.tsx
- packages/ui-components/src/components/Domain/DomainListGrid.tsx
- packages/ui-components/src/components/Domain/DomainListModal.tsx
- packages/ui-components/src/components/Domain/DomainProfileList.tsx
- packages/ui-components/src/components/TokenGallery/NftCard.tsx
- packages/ui-components/src/lib/types/domain.ts
- packages/ui-components/src/lib/types/nfts.ts
- server/pages/[domain]/index.page.tsx
Show the listing price if available.
> Show listing info on domain grid

- packages/ui-components/package.json
- packages/ui-components/src/locales/en.json
- server/pages/[domain]/index.page.tsx
Update redirect logic for search page.
> Change redirect logic
